version: 2
jobs:
  build_then_deploy:
    branches:
      only:
      - master
    docker:
    - image: circleci/node:12-browsers
    steps:
    - checkout
    - restore_cache:
        key: IntenseDataViz-{{ .Branch }}
    - run: cd client && npm install '@angular/cli'
    - run: cd client && npm install
    - save_cache:
        key: IntenseDataViz-{{ .Branch }}
        paths:
        - "node_modules"
    - run: cd client && node_modules/.bin/ng build --prod
    # - store_artifacts:
    #    path: /client/dist/client
    - run: cd client && node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN