version: 2
jobs:
  build:
    # working_directory: ~/intense-dataviz/client
    docker:
    - image: circleci/node:12-browsers
    steps:
    - checkout
    - restore_cache:
        key: IntenseDataViz-{{ .Branch }} #-{{ checksum "package.json" }}
    - run: npm install '@angular/cli'
    - run: cd client && npm install
    - save_cache:
        key: IntenseDataViz-{{ .Branch }} #-{{ checksum "package.json" }}
        paths:
        - "node_modules"
    # - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
    # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
    - run: cd client && node_modules/.bin/ng build --prod
  deploy:
    # working_directory: ~/intense-dataviz/client
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - restore_cache:
        key: IntenseDataViz-{{ .Branch }} #-{{ checksum "package.json" }}
    - run: npm install 'firebase-tools'
    - save_cache:
        key: IntenseDataViz-{{ .Branch }} #-{{ checksum "package.json" }}
        paths:
        - "node_modules"
    # - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
    # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
    - run: cd client && node_modules/.bin/firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN
workflows:
  version: 2
  build_then_deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build